///////////////////////////////////////////////////////////
//  Conductor.cs
//  Implementation of the Class Conductor
//  Generated by Enterprise Architect
//  Created on:      10-Jul-2016 2:00:04 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CIM.IEC61970.Base.Core;
namespace CIM.IEC61970.Base.Wires {
	/// <summary>
	/// Combination of conducting material with consistent electrical characteristics,
	/// building a single electrical system, used to carry current between points in
	/// the power system.
	/// </summary>
	public class Conductor : ConductingEquipment {

		/// <summary>
		/// Segment length for calculating line section capabilities
		/// </summary>
		public float length;

		public Conductor(){

		}

		~Conductor(){

		}

	}//end Conductor

}//end namespace Wires