///////////////////////////////////////////////////////////
//  Disconnector.cs
//  Implementation of the Class Disconnector
//  Generated by Enterprise Architect
//  Created on:      10-Jul-2016 2:00:04 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CIM.IEC61970.Base.Wires;
namespace CIM.IEC61970.Base.Wires {
	/// <summary>
	/// A manually operated or motor operated mechanical switching device used for
	/// changing the connections in a circuit, or for isolating a circuit or equipment
	/// from a source of power. It is required to open or close circuits when
	/// negligible current is broken or made.
	/// </summary>
	public class Disconnector : Switch {

		public Disconnector(){

		}

		~Disconnector(){

		}

	}//end Disconnector

}//end namespace Wires