///////////////////////////////////////////////////////////
//  EnergyConsumer.cs
//  Implementation of the Class EnergyConsumer
//  Generated by Enterprise Architect
//  Created on:      10-Jul-2016 2:00:04 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CIM.IEC61970.Base.Core;
namespace CIM.IEC61970.Base.Wires {
	/// <summary>
	/// Generic user of energy - a  point of consumption on the power system model.
	/// </summary>
	public class EnergyConsumer : ConductingEquipment {

		/// <summary>
		/// Number of individual customers represented by this demand.
		/// </summary>
		public int customerCount;
		/// <summary>
		/// Used for Yn and Zn connections. True if the neutral is solidly grounded.
		/// </summary>
		public bool grounded;
		/// <summary>
		/// Active power of the load. Load sign convention is used, i.e. positive sign
		/// means flow out from a node.
		/// For voltage dependent loads the value is at rated voltage.
		/// Starting value for a steady state solution.
		/// </summary>
		public float p;
		/// <summary>
		/// Active power of the load that is a fixed quantity. Load sign convention is used,
		/// i.e. positive sign means flow out from a node.
		/// </summary>
		public float pfixed;
		/// <summary>
		/// Fixed active power as per cent of load group fixed active power. Load sign
		/// convention is used, i.e. positive sign means flow out from a node.
		/// </summary>
		public float pfixedPct;
		/// <summary>
		/// Reactive power of the load. Load sign convention is used, i.e. positive sign
		/// means flow out from a node.
		/// For voltage dependent loads the value is at rated voltage.
		/// Starting value for a steady state solution.
		/// </summary>
		public float q;
		/// <summary>
		/// Reactive power of the load that is a fixed quantity. Load sign convention is
		/// used, i.e. positive sign means flow out from a node.
		/// </summary>
		public float qfixed;
		/// <summary>
		/// Fixed reactive power as per cent of load group fixed reactive power. Load sign
		/// convention is used, i.e. positive sign means flow out from a node.
		/// </summary>
		public float qfixedPct;

		public EnergyConsumer(){

		}

		~EnergyConsumer(){

		}

	}//end EnergyConsumer

}//end namespace Wires