///////////////////////////////////////////////////////////
//  ProtectedSwitch.cs
//  Implementation of the Class ProtectedSwitch
//  Generated by Enterprise Architect
//  Created on:      10-Jul-2016 2:00:05 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CIM.IEC61970.Base.Wires;
namespace CIM.IEC61970.Base.Wires {
	/// <summary>
	/// A ProtectedSwitch is a switching device that can be operated by
	/// ProtectionEquipment.
	/// </summary>
	public class ProtectedSwitch : Switch {

		public ProtectedSwitch(){

		}

		~ProtectedSwitch(){

		}

	}//end ProtectedSwitch

}//end namespace Wires