///////////////////////////////////////////////////////////
//  SVCControlMode.cs
//  Implementation of the Enumeration SVCControlMode
//  Generated by Enterprise Architect
//  Created on:      10-Jul-2016 2:00:05 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace CIM.IEC61970.Base.Wires {
	/// <summary>
	/// Static VAr Compensator control mode.
	/// </summary>
	public enum SVCControlMode : int {

		reactivePower,
		voltage

	}//end SVCControlMode

}//end namespace Wires