///////////////////////////////////////////////////////////
//  TransformerEnd.cs
//  Implementation of the Class TransformerEnd
//  Generated by Enterprise Architect
//  Created on:      10-Jul-2016 2:00:05 PM
//  Original author: T. Kostic
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CIM.IEC61970.Base.Core;
namespace CIM.IEC61970.Base.Wires {
	/// <summary>
	/// A conducting connection point of a power transformer. It corresponds to a
	/// physical transformer winding terminal.  In earlier CIM versions, the
	/// TransformerWinding class served a similar purpose, but this class is more
	/// flexible because it associates to terminal but is not a specialization of
	/// ConductingEquipment.
	/// </summary>
	public class TransformerEnd : IdentifiedObject {

		/// <summary>
		/// Number for this transformer end, corresponding to the end's order in the power
		/// transformer vector group or phase angle clock number.  Highest voltage winding
		/// should be 1.  Each end within a power transformer should have a unique
		/// subsequent end number.   Note the transformer end number need not match the
		/// terminal sequence number.
		/// </summary>
		public int endNumber;
		/// <summary>
		/// (for Yn and Zn connections) True if the neutral is solidly grounded.
		/// </summary>
		public bool grounded;
		/// <summary>
		/// (for Yn and Zn connections) Resistance part of neutral impedance where
		/// 'grounded' is true.
		/// </summary>
		public float rground;
		/// <summary>
		/// (for Yn and Zn connections) Reactive part of neutral impedance where 'grounded'
		/// is true.
		/// </summary>
		public float xground;
		/// <summary>
		/// Base voltage of the transformer end.  This is essential for PU calculation.
		/// </summary>
		public CIM.IEC61970.Base.Core.BaseVoltage BaseVoltage;
		/// <summary>
		/// Terminal of the power transformer to which this transformer end belongs.
		/// </summary>
		public CIM.IEC61970.Base.Core.Terminal Terminal;

		public TransformerEnd(){

		}

		~TransformerEnd(){

		}

	}//end TransformerEnd

}//end namespace Wires