///////////////////////////////////////////////////////////
//  Bay.cs
//  Implementation of the Class Bay
//  Generated by Enterprise Architect
//  Created on:      10-Jul-2016 2:00:03 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CIM.IEC61970.Base.Core;
namespace CIM.IEC61970.Base.Core {
	/// <summary>
	/// A collection of power system resources (within a given substation) including
	/// conducting equipment, protection relays, measurements, and telemetry.  A bay
	/// typically represents a physical grouping related to modularization of equipment.
	/// 
	/// </summary>
	public class Bay : EquipmentContainer {

		public Bay(){

		}

		~Bay(){

		}

	}//end Bay

}//end namespace Core