///////////////////////////////////////////////////////////
//  ConnectivityNode.cs
//  Implementation of the Class ConnectivityNode
//  Generated by Enterprise Architect
//  Created on:      08-Jul-2016 7:31:29 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CIM.IEC61970.Base.Core;
namespace CIM.IEC61970.Base.Core {
	/// <summary>
	/// Connectivity nodes are points where terminals of AC conducting equipment are
	/// connected together with zero impedance.
	/// </summary>
	public class ConnectivityNode : IdentifiedObject {

		public CIM.IEC61970.Base.Core.BaseVoltage m_BaseVoltage;
		/// <summary>
		/// Container of this connectivity node.
		/// </summary>
		public CIM.IEC61970.Base.Core.ConnectivityNodeContainer ConnectivityNodeContainer;

        private int x;
        private int y;

        public int X
        {
            get { return this.x; }
            set { this.x = value; }
        }
        public int Y
        {
            get { return this.y; }
            set { this.y = value; }
        }
        
        public ConnectivityNode(){
            X = -1;
            Y = -1;
		}

		~ConnectivityNode(){

		}

	}//end ConnectivityNode

}//end namespace Core