///////////////////////////////////////////////////////////
//  PowerSystemResource.cs
//  Implementation of the Class PowerSystemResource
//  Generated by Enterprise Architect
//  Created on:      10-Jul-2016 2:00:04 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CIM.IEC61970.Base.Core;
namespace CIM.IEC61970.Base.Core {
	/// <summary>
	/// A power system resource can be an item of equipment such as a switch, an
	/// equipment container containing many individual items of equipment such as a
	/// substation, or an organisational entity such as sub-control area. Power system
	/// resources can have measurements associated.
	/// </summary>
	public class PowerSystemResource : IdentifiedObject {

		public PowerSystemResource(){

		}

		~PowerSystemResource(){

		}

	}//end PowerSystemResource

}//end namespace Core