///////////////////////////////////////////////////////////
//  VoltageLevel.cs
//  Implementation of the Class VoltageLevel
//  Generated by Enterprise Architect
//  Created on:      10-Jul-2016 2:00:05 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CIM.IEC61970.Base.Core;
namespace CIM.IEC61970.Base.Core {
	/// <summary>
	/// A collection of equipment at one common system voltage forming a switchgear.
	/// The equipment typically consist of breakers, busbars, instrumentation, control,
	/// regulation and protection devices as well as assemblies of all these.
	/// </summary>
	public class VoltageLevel : EquipmentContainer {

		/// <summary>
		/// The bays within this voltage level.
		/// </summary>
		public List<Bay> Bays;
		/// <summary>
		/// The base voltage used for all equipment within the voltage level.
		/// </summary>
		public CIM.IEC61970.Base.Core.BaseVoltage BaseVoltage;

		public VoltageLevel(){

		}

		~VoltageLevel(){

		}

	}//end VoltageLevel

}//end namespace Core